version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/be
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ec2-user
