FROM node:22 AS builder
WORKDIR /app
COPY package.json ./
RUN yarn install
COPY . .
RUN yarn build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app .
EXPOSE 5440

RUN apk add --no-cache aws-cli jq wget
# 1. 엔트리포인트 스크립트 복사
COPY ./docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

RUN wget https://www.amazontrust.com/repository/AmazonRootCA1.pem -O /app/dist/db/AmazonRootCA.pem


RUN npm install pm2@latest -g

# 2. 엔트리포인트로 스크립트 지정
ENTRYPOINT ["docker-entrypoint.sh"]
